cicd update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,9 +27,14 @@ jobs:
       with:
         name: smartmoveback-jar
         path: target/smartmoveback-0.0.1-SNAPSHOT.jar
-
+    
+    - name: Check JAR existence
+      run: test -f target/smartmoveback-0.0.1-SNAPSHOT.jar || { echo "JAR file not found!"; exit 1; }
+      
     - name: Execute JAR File
-      run: sudo kill -9 `sudo lsof -t -i:8080` & sudo java -jar target/smartmoveback-0.0.1-SNAPSHOT.jar
+      run: |
+        sudo kill -9 `sudo lsof -t -i:8080` || true
+        sudo java -jar target/smartmoveback-0.0.1-SNAPSHOT.jar
 
     - name: Login Dockerhub
       env:
